import { useEffect, useState, type ReactNode } from 'react';
import { AlertCircle, CheckCircle2, Copy, Play, Terminal as TerminalIcon } from 'lucide-react';
import { clsx } from 'clsx';
import toast from 'react-hot-toast';
import apiClient from '../../api/client';
import { DashboardPanel } from '../dashboard/DashboardPanel';

interface AutoRemediationProps {
  incident: { id: string };
  sitrep: string;
}

const AutoRemediation = ({ incident, sitrep }: AutoRemediationProps) => {
  const [copied, setCopied] = useState(false);
  const [script, setScript] = useState('');
  const [executing, setExecuting] = useState(false);
  const [output, setOutput] = useState<string[]>([]);

  useEffect(() => {
    if (!sitrep) return;
    const match = sitrep.match(/```(?:bash|sh|cli)\n([\s\S]*?)```/);
    setScript(match?.[1]?.trim() || '');
  }, [sitrep]);

  const handleCopy = () => {
    navigator.clipboard.writeText(script);
    setCopied(true);
    toast.success('Script copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExecute = async () => {
    if (!window.confirm('WARNING: You are about to execute an AI-generated script on your production environment. Are you sure?')) {
      return;
    }

    setExecuting(true);
    setOutput(['Establishing secure bridge to target environment...']);

    try {
      const { data } = await apiClient.post(`/incidents/${incident.id}/remediate`, { script });

      const executionResult = [
        'OK: Bridge established.',
        '> Executing remediation payload...',
        '----------------------------------------',
        ...(data.output ? data.output.split('\n') : ['No standard output returned.']),
        '----------------------------------------',
        'OK: Remediation completed.',
      ];

      if (data.stderr) {
        executionResult.push('WARNING / STDERR:');
        executionResult.push(...data.stderr.split('\n'));
      }

      setOutput(executionResult);
      toast.success('Script executed successfully!');
    } catch (err: any) {
      setOutput([
        'ERROR: Bridge failed or command timed out.',
        err.response?.data?.message || err.message,
      ]);
      toast.error('Execution failed.');
    } finally {
      setExecuting(false);
    }
  };

  if (!script) return null;

  return (
    <DashboardPanel
      title="AI remediation plan"
      description="Automated fix generated by the investigation report."
      action={
        <div className="flex flex-wrap gap-2">
          <button
            onClick={handleExecute}
            disabled={executing}
            className={clsx(
              'inline-flex min-h-10 items-center gap-2 rounded-2xl bg-emerald-600 px-4 text-[12px] font-black text-white shadow-[0_12px_24px_rgba(5,150,105,0.2)] transition hover:-translate-y-0.5 disabled:opacity-60',
              executing && 'cursor-not-allowed'
            )}
          >
            <Play size={14} className={executing ? 'animate-pulse' : ''} />
            {executing ? 'Executing...' : 'Run Fix'}
          </button>
          <button onClick={handleCopy} className="inline-flex min-h-10 items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 text-[12px] font-black text-slate-600 transition hover:-translate-y-0.5">
            {copied ? <CheckCircle2 size={14} className="text-emerald-600" /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
      }
    >
      <div className="space-y-5 p-5">
        {output.length > 0 && (
          <TerminalBlock title="Live Execution Output">
            {output.map((line, index) => (
              <div
                key={`${line}-${index}`}
                className={clsx(
                  'py-0.5',
                  line.startsWith('OK:') && 'text-emerald-300',
                  line.startsWith('ERROR:') && 'text-red-400',
                  line.startsWith('WARNING') && 'text-amber-300',
                  !line.startsWith('OK:') && !line.startsWith('ERROR:') && !line.startsWith('WARNING') && 'text-slate-400'
                )}
              >
                {line}
              </div>
            ))}
          </TerminalBlock>
        )}

        <TerminalBlock title="sh --generated-fix.sh">
          {script.split('\n').map((line, index) => (
            <div key={`${line}-${index}`} className="flex rounded px-2 py-0.5 transition hover:bg-slate-800/70">
              <span className="mr-4 w-5 select-none text-right text-slate-700">{index + 1}</span>
              <span className="mr-3 text-slate-500">$</span>
              <span className="text-emerald-300">{line}</span>
            </div>
          ))}
        </TerminalBlock>

        <div className="flex items-start gap-3 rounded-2xl border border-amber-100 bg-amber-50 p-4">
          <AlertCircle size={17} className="mt-0.5 shrink-0 text-amber-600" />
          <p className="text-[12px] font-semibold leading-6 text-amber-800">
            <strong className="font-black uppercase tracking-[0.08em]">Safety advisory:</strong> Review the generated script carefully before execution. AI-generated commands can have unintended side effects in production environments.
          </p>
        </div>
      </div>
    </DashboardPanel>
  );
};

function TerminalBlock({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="overflow-hidden rounded-[22px] bg-[#07111f] shadow-inner">
      <div className="flex items-center justify-between border-b border-white/10 px-4 py-3">
        <div className="flex items-center gap-2 text-slate-500">
          <TerminalIcon size={14} />
          <span className="font-mono text-[10px] font-black uppercase tracking-[0.16em]">{title}</span>
        </div>
        <div className="flex gap-1.5">
          <span className="h-2.5 w-2.5 rounded-full bg-slate-700" />
          <span className="h-2.5 w-2.5 rounded-full bg-slate-700" />
          <span className="h-2.5 w-2.5 rounded-full bg-slate-700" />
        </div>
      </div>
      <div className="max-h-80 overflow-auto p-4 font-mono text-[11px] leading-6">
        {children}
      </div>
    </div>
  );
}

export default AutoRemediation;
